//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Example
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Example()
        {
            this.ExampleCategory = new HashSet<ExampleCategory>();
            this.Marked = new HashSet<Marked>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.TimeSpan> TimeSpent { get; set; }
        public string FileName { get; set; }
        public Nullable<int> OrdinalNumber { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExampleCategory> ExampleCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marked> Marked { get; set; }
    }
}
