//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPassword
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<bool> WrongEmail { get; set; }
        public string Description { get; set; }
        public string InsertedEmail { get; set; }
        public string GeneratedKey { get; set; }
    
        public virtual User User { get; set; }
    }
}
