//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marked
    {
        public int Id { get; set; }
        public Nullable<int> ExampleId { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
        public Nullable<int> SentenceId { get; set; }
        public Nullable<int> EntityId { get; set; }
    
        public virtual Example Example { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
