//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLE.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MLEEntities : DbContext
    {
        public MLEEntities()
            : base("name=MLEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Example> Example { get; set; }
        public virtual DbSet<ExampleType> ExampleType { get; set; }
        public virtual DbSet<Marked> Marked { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Subcategory> Subcategory { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserExample> UserExample { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<JsonData> JsonData { get; set; }
        public virtual DbSet<ForgotPassword> ForgotPassword { get; set; }
    }
}
